# Generated by Django 2.1.7 on 2019-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190217_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='AttemptLog',
            field=models.IntegerField(default=0),
        ),
    ]
