# Generated by Django 2.1.7 on 2019-02-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190219_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='AttemptLog',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Attempts',
            field=models.IntegerField(default=0),
        ),
    ]
