# Generated by Django 2.1.7 on 2019-02-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190221_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Attempts',
            new_name='AttemptLogs',
        ),
    ]
