# Generated by Django 2.1.7 on 2019-02-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190221_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='AttemptLogs',
        ),
    ]
