# Generated by Django 2.1.7 on 2019-02-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_attemptlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Attempts',
            field=models.IntegerField(default=0),
        ),
    ]
