# Generated by Django 2.1.7 on 2019-02-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_hintpressed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='HintPressed',
        ),
        migrations.AddField(
            model_name='customuser',
            name='HintP',
            field=models.BooleanField(default=False),
        ),
    ]
