# Generated by Django 2.1.7 on 2019-02-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190223_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='HintP',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
