# Generated by Django 2.1.7 on 2019-02-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_hintp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='TimeLog',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
