# Generated by Django 2.1.2 on 2019-01-09 10:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('AID', models.IntegerField(primary_key=True, serialize=False)),
                ('AName', models.CharField(max_length=3000)),
                ('AText', models.TextField()),
                ('Image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInfo',
            fields=[
                ('QID', models.IntegerField(primary_key=True, serialize=False)),
                ('QText', models.TextField()),
                ('Image', models.URLField(blank=True)),
                ('Answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=10)),
                ('CloseAnswer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=20)),
            ],
        ),
    ]
