# Generated by Django 2.1.7 on 2019-02-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('SID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.TextField(blank=True)),
                ('Body', models.TextField(blank=True)),
                ('Hanger', models.TextField(blank=True)),
            ],
        ),
    ]
