# Generated by Django 2.1.2 on 2019-01-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasterEggs',
            fields=[
                ('EID', models.IntegerField(primary_key=True, serialize=False)),
                ('PWeight', models.IntegerField()),
                ('Desc', models.CharField(max_length=1000)),
                ('AID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Achievements')),
            ],
        ),
    ]
