# Generated by Django 2.1.2 on 2018-12-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_Info',
            new_name='QuestionInfo',
        ),
    ]
