# Generated by Django 2.1.2 on 2019-01-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20190103_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninfo',
            name='Answer_Provided',
        ),
    ]
