# Generated by Django 2.1.7 on 2019-02-20 19:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20190218_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninfo',
            name='Solved',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default='', size=None),
            preserve_default=False,
        ),
    ]
