# Generated by Django 2.1.2 on 2018-12-25 05:55

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achievements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QID', models.IntegerField(primary_key=True, serialize=False)),
                ('QText', models.TextField()),
                ('Image', models.URLField(blank=True)),
                ('Answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=10)),
                ('CloseAnswer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=20)),
            ],
        ),
    ]
