# Generated by Django 2.1.7 on 2019-02-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManualRegConfirm',
        ),
    ]
