# Generated by Django 2.1.7 on 2019-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginSignup', '0002_delete_manualregconfirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('IPAdd', models.CharField(blank=True, max_length=50)),
                ('AnswerSub', models.CharField(blank=True, max_length=100)),
                ('TimeStamp', models.TimeField(blank=True)),
                ('ViewName', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
